# Generated by Django 5.0.3 on 2024-03-10 10:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeBook',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('underlier_ticker', models.CharField(max_length=25)),
                ('product_type', models.CharField(max_length=25)),
                ('payoff', models.CharField(max_length=10)),
                ('trade_date', models.DateField()),
                ('trade_maturity', models.DateField()),
                ('strike', models.FloatField()),
                ('dividend', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(default='kbienias', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DerivativePrice',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('valuation_date', models.DateField()),
                ('price_status', models.CharField(max_length=25)),
                ('analytical_price', models.FloatField()),
                ('extra_price', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(default='kbienias', max_length=100)),
                ('trade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiener.tradebook')),
            ],
        ),
    ]
