# Generated by Django 5.1.4 on 2025-03-12 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeBook',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('underlying_ticker', models.CharField(max_length=25)),
                ('product_type', models.CharField(max_length=25)),
                ('payoff', models.CharField(max_length=10)),
                ('trade_date', models.DateField()),
                ('trade_maturity', models.DateField()),
                ('strike', models.FloatField()),
                ('dividend', models.FloatField()),
                ('option_style', models.CharField(blank=True, max_length=50, null=True)),
                ('structured_params', models.JSONField(blank=True, null=True)),
                ('user_id', models.CharField(default='kbienias', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DerivativePrice',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('valuation_date', models.DateField()),
                ('price_status', models.CharField(max_length=25)),
                ('official_price', models.FloatField()),
                ('pricing_framework', models.CharField(blank=True, max_length=50, null=True)),
                ('pricing_method', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.CharField(default='kbienias', max_length=100)),
                ('trade_id', models.ForeignKey(db_column='trade_id', on_delete=django.db.models.deletion.CASCADE, to='wiener.tradebook')),
            ],
        ),
    ]
