# Generated by Django 5.1.4 on 2025-02-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradebook',
            name='option_style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
