# Generated by Django 5.1.4 on 2025-03-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradebook',
            name='payoff',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
