# Generated by Django 5.1.4 on 2025-03-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiener', '0002_alter_tradebook_payoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradebook',
            name='strike',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
