# Generated by Django 5.1.4 on 2025-02-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiener', '0003_tradebook_structured_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivativeprice',
            name='confidence_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derivativeprice',
            name='market_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derivativeprice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derivativeprice',
            name='pricing_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
