"""
Django settings for numeraire_web project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Numeraire++ repository root (contains sql/schema_v1.sql, db.sqlite3, .env).
REPO_ROOT = BASE_DIR.parent
_env_file = REPO_ROOT / '.env'
if _env_file.is_file():
    for _line in _env_file.read_text(encoding='utf-8').splitlines():
        _line = _line.strip()
        if _line and not _line.startswith('#') and '=' in _line:
            _k, _, _v = _line.partition('=')
            os.environ.setdefault(_k.strip(), _v.strip())

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-fallback')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Product version shown in the Journal footer (semver, leading 0 = pre-1.0).
APP_VERSION = os.environ.get('NUMERAIRE_APP_VERSION', '0.4.2')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'journal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Deny by default: every view needs a logged-in user unless decorated with
    # @login_not_required. Django's own auth and admin login views already are.
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'journal:dashboard'
LOGOUT_REDIRECT_URL = 'journal:landing'

# base.html renders `alert-{{ message.tags }}`; Bootstrap spells the error level 'danger'.
MESSAGE_TAGS = {message_constants.ERROR: 'danger'}

ROOT_URLCONF = 'numeraire_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'numeraire_web.context_processors.app_meta',
            ],
            # Explicit so runserver reloads pick up custom filters without a cold start.
            'libraries': {
                'journal_fmt': 'journal.templatetags.journal_fmt',
            },
            'builtins': [
                'journal.templatetags.journal_fmt',
            ],
        },
    },
]

WSGI_APPLICATION = 'numeraire_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Two databases on purpose:
#   default   - Django's own tables (auth, sessions, admin log), migrated normally.
#   numeraire - the C++ batch database. Schema is owned by sql/schema_v1.sql and is
#               never migrated from here; the `journal` app is routed to it by
#               numeraire_web.db_router.NumeraireRouter.


def _numeraire_db_path():
    """Resolve the C++ SQLite file the same way numeraire_viz and dev_main do."""
    raw = os.environ.get('NUMERAIRE_DB_PATH', '').strip()
    if not raw:
        env_file = REPO_ROOT / '.env'
        if env_file.is_file():
            for line in env_file.read_text(encoding='utf-8').splitlines():
                key, sep, value = line.strip().partition('=')
                if sep and key.strip() == 'NUMERAIRE_DB_PATH':
                    raw = value.strip()
                    break
    path = Path(raw or 'db.sqlite3').expanduser()
    return path if path.is_absolute() else (REPO_ROOT / path).resolve()


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'web_app.sqlite3',
    },
    'numeraire': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _numeraire_db_path(),
        # EOD batches hold a write lock while running (journal_mode is `delete`).
        'OPTIONS': {'timeout': 15},
    },
}

DATABASE_ROUTERS = ['numeraire_web.db_router.NumeraireRouter']


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
