# Generated by Django 4.2.6 on 2023-11-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geralt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeBookModel',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('underlier_ticker', models.CharField(max_length=10)),
                ('product_type', models.CharField(max_length=25)),
                ('payoff', models.CharField(max_length=10)),
                ('trade_date', models.DateField()),
                ('trade_maturity', models.DateField()),
                ('strike', models.FloatField()),
                ('dividend', models.FloatField()),
            ],
        ),
    ]
