# Generated by Django 5.2.16 on 2026-07-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityDailyEod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.TextField()),
                ('as_of', models.DateField()),
                ('session_calendar', models.TextField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('currency', models.TextField()),
                ('volume', models.FloatField(blank=True, null=True)),
                ('vwap', models.FloatField(blank=True, null=True)),
                ('trade_count', models.IntegerField(blank=True, null=True)),
                ('source', models.TextField()),
                ('timespan', models.TextField()),
                ('adjusted', models.IntegerField()),
                ('provider_timestamp_utc_ms', models.BigIntegerField(blank=True, null=True)),
                ('ingested_at', models.TextField()),
            ],
            options={
                'verbose_name': 'Equity daily EOD',
                'verbose_name_plural': 'Equity daily EOD',
                'db_table': 'equity_daily_eod',
                'ordering': ['-as_of', 'ticker'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndexDailyEod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.TextField()),
                ('as_of', models.DateField()),
                ('session_calendar', models.TextField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('currency', models.TextField()),
                ('volume', models.FloatField(blank=True, null=True)),
                ('vwap', models.FloatField(blank=True, null=True)),
                ('trade_count', models.IntegerField(blank=True, null=True)),
                ('source', models.TextField()),
                ('timespan', models.TextField()),
                ('adjusted', models.IntegerField()),
                ('provider_timestamp_utc_ms', models.BigIntegerField(blank=True, null=True)),
                ('ingested_at', models.TextField()),
            ],
            options={
                'verbose_name': 'Index daily EOD',
                'verbose_name_plural': 'Index daily EOD',
                'db_table': 'index_daily_eod',
                'ordering': ['-as_of', 'ticker'],
                'managed': False,
            },
        ),
    ]
