# Generated by Django 5.2.16 on 2026-07-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_equity_index_daily_eod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParCurveEod',
            fields=[
                ('pk', models.CompositePrimaryKey('curve_id', 'as_of', blank=True, editable=False, primary_key=True, serialize=False)),
                ('curve_id', models.TextField()),
                ('as_of', models.DateField()),
                ('currency', models.TextField()),
                ('curve_kind', models.TextField()),
                ('source', models.TextField()),
                ('day_count', models.TextField()),
                ('session_calendar', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('ingested_at', models.TextField()),
            ],
            options={
                'verbose_name': 'Par curve',
                'db_table': 'par_curve_eod',
                'ordering': ['-as_of', 'curve_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParCurvePointEod',
            fields=[
                ('pk', models.CompositePrimaryKey('curve_id', 'as_of', 'tenor', blank=True, editable=False, primary_key=True, serialize=False)),
                ('curve_id', models.TextField()),
                ('as_of', models.DateField()),
                ('tenor', models.TextField()),
                ('tenor_days', models.IntegerField(blank=True, null=True)),
                ('instrument_type', models.TextField()),
                ('fred_series_id', models.TextField()),
                ('quoted_rate', models.FloatField()),
                ('quoted_price', models.FloatField(blank=True, null=True)),
                ('quote_style', models.TextField()),
            ],
            options={
                'verbose_name': 'Par curve point',
                'db_table': 'par_curve_point_eod',
                'ordering': ['as_of', 'tenor_days', 'tenor'],
                'managed': False,
            },
        ),
    ]
